export const credentials = [
  {
    name: "Spain",
    username: "admin1",
    password: "adminpass1",
    details: {
      commitsList: [
        {
          user: "John Doe",
          commit: "Updated user interface",
          date: "June 12, 2021",
        },
        {
          user: "Jane Smith",
          commit: "Fixed bugs in the application",
          date: "June 10, 2021",
        },
        {
          user: "Michael Brown",
          commit: "Added new features",
          date: "June 8, 2021",
        },
      ],
      chartData: [
        { name: "January", purchase: 15 },
        { name: "February", purchase: 22 },
        { name: "March", purchase: 5 },
        { name: "April", purchase: 43 },
        { name: "May", purchase: 22 },
        { name: "June", purchase: 65 },
        { name: "July", purchase: 43 },
        { name: "August", purchase: 23 },
        { name: "September", purchase: 10 },
        { name: "October", purchase: 35 },
        { name: "November", purchase: 80 },
        { name: "December", purchase: 125 },
      ],
      pieoneData: [
        { label: "label1", value: 60, fill: "#ff6384" },
        { label: "label2", value: 40, fill: "#36a2eb" },
      ],
      pietwoData: [
        { label: "label1", value: 30, fill: "#ffce56" },
        { label: "label2", value: 25, fill: "#4bc0c0" },
        { label: "label3", value: 20, fill: "#9966ff" },
        { label: "label4", value: 15, fill: "#ff9f40" },
        { label: "label5", value: 10, fill: "#ff6384" },
      ],
    },
  },
  {
    name: "Nigeria",
    username: "user1",
    password: "userpass1",
    details: {
      commitsList: [
        {
          user: "Alice Johnson",
          commit: "Improved performance",
          date: "June 12, 2021",
        },
        {
          user: "Chris Evans",
          commit: "Minor updates",
          date: "June 11, 2021",
        },
        {
          user: "Sarah Connor",
          commit: "Refactored code",
          date: "June 9, 2021",
        },
      ],
      chartData: [
        { name: "January", purchase: 33 },
        { name: "February", purchase: 22 },
        { name: "March", purchase: 5 },
        { name: "April", purchase: 43 },
        { name: "May", purchase: 55 },
        { name: "June", purchase: 65 },
        { name: "July", purchase: 43 },
        { name: "August", purchase: 23 },
        { name: "September", purchase: 10 },
        { name: "October", purchase: 15 },
        { name: "November", purchase: 80 },
        { name: "December", purchase: 15 },
      ],
      pieoneData: [
        { label: "label1", value: 50, fill: "#ff6384" },
        { label: "label2", value: 50, fill: "#36a2eb" },
      ],
      pietwoData: [
        { label: "label1", value: 25, fill: "#ffce56" },
        { label: "label2", value: 20, fill: "#4bc0c0" },
        { label: "label3", value: 15, fill: "#9966ff" },
        { label: "label4", value: 10, fill: "#ff9f40" },
        { label: "label5", value: 30, fill: "#ff6384" },
      ],
    },
  },
  {
    name: "Ghana",
    username: "admin2",
    password: "adminpass2",
    details: {
      commitsList: [
        {
          user: "Mike Brown",
          commit: "Updated documentation",
          date: "June 12, 2021",
        },
        {
          user: "Emily Taylor",
          commit: "Fixed issues",
          date: "June 11, 2021",
        },
        {
          user: "David Lee",
          commit: "Improved code quality",
          date: "June 10, 2021",
        },
      ],
      chartData: [
        { name: "January", purchase: 15 },
        { name: "February", purchase: 22 },
        { name: "March", purchase: 5 },
        { name: "April", purchase: 23 },
        { name: "May", purchase: 22 },
        { name: "June", purchase: 65 },
        { name: "July", purchase: 89 },
        { name: "August", purchase: 23 },
        { name: "September", purchase: 10 },
        { name: "October", purchase: 35 },
        { name: "November", purchase: 10 },
        { name: "December", purchase: 15 },
      ],
      pieoneData: [
        { label: "label1", value: 55, fill: "#ff6384" },
        { label: "label2", value: 45, fill: "#36a2eb" },
      ],
      pietwoData: [
        { label: "label1", value: 35, fill: "#ffce56" },
        { label: "label2", value: 30, fill: "#4bc0c0" },
        { label: "label3", value: 20, fill: "#9966ff" },
        { label: "label4", value: 10, fill: "#ff9f40" },
        { label: "label5", value: 5, fill: "#ff6384" },
      ],
    },
  },
  {
    name: "Canada",
    username: "user2",
    password: "userpass2",
    details: {
      commitsList: [
        {
          user: "Hannah White",
          commit: "Updated dependencies",
          date: "June 12, 2021",
        },
        {
          user: "Kevin White",
          commit: "Minor updates",
          date: "June 11, 2021",
        },
        {
          user: "Olivia Martin",
          commit: "Improved performance",
          date: "June 10, 2021",
        },
      ],
      chartData: [
        { name: "January", purchase: 8 },
        { name: "February", purchase: 18 },
        { name: "March", purchase: 28 },
        { name: "April", purchase: 38 },
        { name: "May", purchase: 48 },
        { name: "June", purchase: 58 },
        { name: "July", purchase: 68 },
        { name: "August", purchase: 78 },
        { name: "September", purchase: 88 },
        { name: "October", purchase: 98 },
        { name: "November", purchase: 108 },
        { name: "December", purchase: 118 },
      ],
      pieoneData: [
        { label: "label1", value: 60, fill: "#ff6384" },
        { label: "label2", value: 40, fill: "#36a2eb" },
      ],
      pietwoData: [
        { label: "label1", value: 40, fill: "#ffce56" },
        { label: "label2", value: 30, fill: "#4bc0c0" },
        { label: "label3", value: 20, fill: "#9966ff" },
        { label: "label4", value: 10, fill: "#ff9f40" },
      ],
    },
  },
  {
    name: "George Harris",
    username: "admin3",
    password: "adminpass3",
    details: {
      commitsList: [
        {
          user: "Samantha Brown",
          commit: "Improved code quality",
          date: "June 12, 2021",
        },
        {
          user: "Michael Davis",
          commit: "Fixed issues",
          date: "June 11, 2021",
        },
        {
          user: "Emily Johnson",
          commit: "Updated documentation",
          date: "June 10, 2021",
        },
      ],
      chartData: [
        { name: "January", purchase: 12 },
        { name: "February", purchase: 22 },
        { name: "March", purchase: 32 },
        { name: "April", purchase: 42 },
        { name: "May", purchase: 52 },
        { name: "June", purchase: 62 },
        { name: "July", purchase: 72 },
        { name: "August", purchase: 82 },
        { name: "September", purchase: 92 },
        { name: "October", purchase: 102 },
        { name: "November", purchase: 112 },
        { name: "December", purchase: 122 },
      ],
      pieoneData: [
        { label: "label1", value: 65, fill: "#ff6384" },
        { label: "label2", value: 35, fill: "#36a2eb" },
      ],
      pietwoData: [
        { label: "label1", value: 45, fill: "#ffce56" },
        { label: "label2", value: 35, fill: "#4bc0c0" },
        { label: "label3", value: 20, fill: "#9966ff" },
      ],
    },
  },
];
